- name: Deploy to EC2
  hosts: localhost
  connection: local

  tasks:
    - name: Launch EC2 Instance
      ec2:
        instance_type: t2.micro
        image: 
        region: us-east-1
        key_name: devops
        vpc_subnet_id: subnet-0a4eedf42968bcd28
        count: 1
        group: eshop
        assign_public_ip: yes
        wait: yes
        aws_access_key: "{{ access_key }}" 
        aws_secret_key: "{{ secret_key }}" 
        security_token: "{{ session_token }}" 
      